version: '3.5'

services:
  cluster-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    container_name: cluster-server
    environment:
      CENTRAL_SERVER_LINK: http://multicluster-central-api:5000
      PORT: 5141
      HOST_IP: 127.0.0.1
      TEST_PORT: 5100
      CLUSTER_NAME: cluster-server
      HOST: '0.0.0.0'
    ports:
      - 5141:5100

    command: ["python", "starter.py", "-v"]

    external_links:
      - multicluster-central-api
    networks:
      - multicluster
    volumes:
      - muticlusterserver:/data

  cluster-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    container_name: cluster-server-2
    environment:
      CENTRAL_SERVER_LINK: http://multicluster-central-api:5000
      PORT: 5142
      HOST_IP: 127.0.0.2
      TEST_PORT: 5101
      CLUSTER_NAME: cluster-server-2
      HOST: '0.0.0.0'
    ports:
      - 5142:5101

    command: ["python", "starter.py", "-v"]

    external_links:
      - multicluster-central-api
    networks:
      - multicluster
    volumes:
      - muticlusterserver2:/data

  cluster-server-3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    container_name: cluster-server-3
    environment:
      CENTRAL_SERVER_LINK: http://multicluster-central-api:5000
      PORT: 5143
      HOST_IP: 127.0.0.3
      TEST_PORT: 5102
      CLUSTER_NAME: cluster-server-3
      HOST: '0.0.0.0'
    ports:
      - 5144:5102

    command: ["python", "starter.py", "-v"]

    external_links:
      - multicluster-central-api
    networks:
      - multicluster
    volumes:
      - muticlusterserver3:/data
  
networks:
  multicluster:
    external: true

volumes:
  muticlusterserver:
  muticlusterserver2:
  muticlusterserver3:
