version: '3.5'

services:
  cluster-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    container_name: cluster-server
    volumes:
      - .:/app
    environment:
      CENTRAL_SERVER_LINK: http://multicluster-central-api
      PORT: 5141
    ports:
      - 5141:5141
    command: ["python", "server.py"]
  
  # cluster-client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   container_name: cluster-client
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 5140:5141
  #   depends_on:
  #     - cluster-server
  #   command: ["python", "client.py"]
  
  # cluster-client-2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   container_name: cluster-client-2
  #   volumes:
  #     - .:/app
  #   environment:
  #     - PORT=5500
  #   ports:
  #     - 5500:5500
  #   depends_on:
  #     - cluster-server
  #   command: ["python", "client.py"]
  
networks:
  multicluster:
    external: true
# volumes:
#   postgres_data: