version: '3.8'

services:

  graphite:
    image: graphiteapp/graphite-statsd:latest
    restart: always
    container_name: graphite
    network_mode: "host"
    volumes:
    - ./storage:/opt/graphite/storage
    - ./storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf

  iperf3:
    build:
      context: .
      dockerfile: Dockerfile-iperf3
    restart: always
    container_name: "iperf3"
    network_mode: "host"
    command: iperf3 -s -V -d -p 5201

  peer-srv:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    container_name: "peer-srv"
    network_mode: "host"
    environment:
      VIEWSERVER: "http://view.cranecloud.africa:5000"
      CARBON_PORT: 2003
      DELAY: 600 #5 minute delay for the graphite pushes
      PORT: 5001
      IPERF: 5201
    volumes:
      - peersrv:/data

  peer-clt:
    build:
      context: .
      dockerfile: Dockerfile-client
    restart: "always"
    container_name: "peer-clt"
    network_mode: "host"
    environment:
      VIEWSERVER: "http://view.cranecloud.africa:5000"
      CARBON_PORT: 2003
      DELAY: 600 #5 minute delay for the graphite pushes
      PORT: 5001
      IPERF: 5201
      W1P: 0.4
      W1M: 0.3
      W1D: 0.3
      W1T: 0.4
      W1L: 0.4
      W1J: 0.2
      W1A: 1
      W2R: 0.35
      W2N: 0.45
      W2A: 0.2
    volumes:
      - peerclt:/data

volumes:
  storage:
  conf:
  peersrv:
  peerclt: