version: '3.8'

services:

  graphite:
    image: graphiteapp/graphite-statsd:latest
    restart: always
    container_name: graphite
    network_mode: "host"
    volumes:
    - ./storage:/opt/graphite/storage

  iperf3:
    build:
      context: .
      dockerfile: Dockerfile-iperf3
    restart: always
    container_name: "iperf3"
    network_mode: "host"
    command: iperf3 -s -V -d -p 5201

  peer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    container_name: peer
    network_mode: "host"
    environment:
      VIEWSERVER: "http://view.cranecloud.africa:5000"
      CARBON_SERVER: '0.0.0.0'
      CARBON_PORT: 2003
      DELAY: 600 #5 minute delay for the graphite pushes
      PORT: 5001
    command: ["python", "init.py", "-v"]
    volumes:
      - peer:/data

volumes:
  storage:
  peer:
