---
- hosts: peer
  remote_user: amwotil
  become: true
  tasks:
    - name: Clean the multi-cluster setup for the peers
      command: make stop
      args:
        chdir: /users/amwotil/sinendet/peerNode
