---
- hosts: cloudlab
  remote_user: amwotil
  become: true
  tasks:
    - name: stop the LE protocol
    shell: "pkill -f /users/amwotil/noler/multi-cluster/peerNode/app_le.py"
    - name: delete the directory
      file:
        state: absent
        path: /users/amwotil/noler
