---
- hosts: peer
  remote_user: ubuntu
  become: true
  tasks:
    - name: Clean the multi-cluster setup for the peers
      command: make clean
      args:
        chdir: /home/ubuntu/multi-cluster/peerNode

    - name: Delete contents & directory of the user
      file:
        state: absent
        path: /home/ubuntu/multi-cluster/
