---
- hosts: peer
  remote_user: amwotil
  become: true
  tasks:
    - name: Clean the multi-cluster setup for the peers
      command: make clean
      args:
        chdir: /users/amwotil/sinendet/peerNode

    - name: Delete contents & directory of the user Alex
      file:
        state: absent
        path: /users/amwotil/sinendet/